version: '3.8'

services: 
  api:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile.dev
  
  storefront:
    build: 
      context: ./saleor-storefront
      dockerfile: ./Dockerfile.dev
    ports: 
      - 3000:3000
    restart: unless-stopped
    command: npm start -- --host 0.0.0.0
    volumes:
      - ./saleor-storefront/:/app:cached
      - /app/node_modules/
    networks: 
      - saleor-frontend-tier
  
  dashboard:
    build:
      context: ./saleor-dashboard
      dockerfile: ./Dockerfile.dev
    ports:
      - 9000:9000
    restart: unless-stopped
    volumes:
      - ./saleor-dashboard/:/app:cached
      - /app/node_modules/
    env_file: ./saleor-dashboard/local.env
    command: npm start -- --host 0.0.0.0
    networks: 
      - saleor-frontend-tier
  
  worker:
    build:
      context: ./saleor
      dockerfile: ./Celery.Dockerfile
  
  nginx:
    build:
      context: ./saleor-nginx
      dockerfile: dockerfile.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - saleor-tmp:/tmp
    networks: 
      - saleor-frontend-tier
      - saleor-backend-tier
    depends_on:
      - api
      - storefront
      - dashboard

networks: 
  saleor-frontend-tier:
