version: '3.8'

services: 
  api:
    build:
      context: ./saleor
      dockerfile: ./Dockerfile
  
  worker:
    build:
      context: ./saleor
      dockerfile: ./Celery.Dockerfile
  
  nginx:
    build:
      context: ./saleor-nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - saleor-tmp:/tmp
